USE [master]
GO

/****** Object:  Database [Raceday]    Script Date: 9/2/2026 11:12:19 AM ******/
CREATE DATABASE [Raceday]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Raceday', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS03\MSSQL\DATA\Raceday.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Raceday_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS03\MSSQL\DATA\Raceday_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Raceday].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Raceday] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Raceday] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Raceday] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Raceday] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Raceday] SET ARITHABORT OFF 
GO

ALTER DATABASE [Raceday] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Raceday] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Raceday] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Raceday] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Raceday] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Raceday] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Raceday] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Raceday] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Raceday] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Raceday] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Raceday] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Raceday] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Raceday] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Raceday] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Raceday] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Raceday] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Raceday] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Raceday] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Raceday] SET  MULTI_USER 
GO

ALTER DATABASE [Raceday] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Raceday] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Raceday] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Raceday] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Raceday] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Raceday] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Raceday] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [Raceday] SET QUERY_STORE = ON
GO

ALTER DATABASE [Raceday] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Raceday] SET  READ_WRITE 
GO

